name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout Code
      id: git_checkout
      uses: actions/checkout@v1
    
    - name: DockerHub Build And Push
      id: dockerhub_build_push
      uses: Abhishek-070/Dockerhub-Build-Push@67adb9a9055400bd6366b96b5b53f44385ab2743
      with:
        registry_url: 'docker.io'
        repository_name: 'debian-android-sdk-ndk'
        user_name: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        # version is all major: debian.sdk.ndk
        image_version: '29'
        docker_file: '.'
